backend:
  name: github
  repo: think-active-labs/not-equal # Path to your Github/Gitlab repository
  branch: main # Branch to update
  base_url: https://not-equal-netlify-cms-github-oauth-provider.vercel.app # Path to ext auth provider

media_folder: public/uploads
public_folder: /uploads

collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "About"
        name: "about"
        file: "content/about.md"
        format: "frontmatter"
        fields:
          - {
              label: "Body",
              name: "body",
              widget: "markdown",
              hint: "Main content goes here.",
            }
      - label: "Home"
        name: "home"
        file: "content/index.md"
        format: "frontmatter"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Description", name: "description", widget: "string" }
          - { label: "Header Image", name: "image", widget: "image" }
          - {
              label: "Body",
              name: "body",
              widget: "markdown",
              hint: "Main content goes here.",
            }
          - label: "Theme Order"
            name: "theme_order"
            widget: list
            fields:
              - {
                  label: "Theme Page",
                  name: "slug",
                  widget: "relation",
                  collection: "theme-pages",
                  value_field: "slug",
                  search_fields: ["title", "slug"],
                }
  - name: "theme-pages"
    label: "Theme Pages"
    folder: "content/themes"
    create: true
    slug: "{{slug}}"
    format: "frontmatter"
    fields:
      - {
          label: "Title",
          name: "title",
          widget: "string",
          hint: "Title of the theme.",
          required: true,
        }
      - {
          label: "Description",
          name: "description",
          widget: "string",
          hint: "Short tag line to describe the theme.",
        }
      - {
          label: "Slug",
          name: "slug",
          widget: "string",
          hint: "The website path of the theme (use dashes instead of spaces) i.e. entering digital-security-for-all will show as not-equal.tech/digital-security-for-all. Note: use lowercase text separated by dashes. Do not use slashes in the slug.",
          required: true,
        }
      - {
          label: "Image",
          name: "image",
          widget: "image",
          hint: "Image that describes the theme (used on home page and theme page).",
        }
      - {
          label: "Body",
          name: "body",
          widget: "markdown",
          hint: "Main page body of the project. If you wish to add custom widgets below this text, use the Page Sections below.",
        }
  - name: "projects"
    label: "Projects"
    folder: "content/projects"
    create: true
    slug: "{{slug}}"
    format: "frontmatter"
    fields:
      - {
          label: "Title",
          name: "title",
          widget: "string",
          hint: "Enter the project title (this will be used as your url i.e. Digital Transformation will become /digital-transformation",
          required: true,
        }
      - {
          label: "Description",
          name: "description",
          widget: "string",
          hint: "Short sentence or two describing the project (used on the project overview pages).",
        }
      - label: "Header Image"
        name: "image"
        widget: "image"
        hint: "Header image displayed at the top of the project page and on the theme projects pages."
        required: true
        media_library:
          config:
            multiple: false
      - {
          label: "Themes",
          name: "themes",
          widget: "relation",
          collection: "theme-pages",
          value_field: "slug",
          search_fields: ["slug", "title"],
          multiple: true,
        }
      - {
          label: "Project Type",
          name: "project_type",
          widget: "relation",
          collection: "project-types-config.project-types",
          value_field: "type",
          search_fields: ["type"],
          multiple: false,
        }
      - label: "Project Lead(s)"
        name: "project_lead"
        widget: "list"
        summary: "{{fields.name}}"
        fields:
          - {
              label: "Project Lead",
              name: "name",
              widget: "string",
              hint: "Enter the name and affiliation of the lead project coordinator. e.g. John Doe, Lecturer in Computer Science, University of Somewhere",
            }
          - {
              label: "Project Lead Email",
              name: "email",
              widget: "string",
              hint: "Enter the email of the lead project coordinator.",
              required: false,
            }
      - label: "Co-investigator(s)"
        name: "investigators"
        widget: "list"
        summary: "{{fields.name}}"
        fields:
          - {
              label: "Investigator",
              name: "name",
              widget: "string",
              hint: "Enter the name and affiliation of the co-investigators. e.g. John Doe, Lecturer in Computer Science, University of Somewhere",
            }
          - {
              label: "Investigator Email",
              name: "email",
              widget: "string",
              hint: "Enter the email of the project co-investigators.",
              required: false,
            }
      - label: "Partner Images"
        name: "partners"
        widget: "list"
        summary: "{{fields.name}} - {{fields.link}}"
        hint: "Project partner images (shown on left hand side)."
        fields:
          - label: "Name"
            name: "name"
            widget: "string"
            hint: "Name of project partner."
          - label: "Link"
            name: "link"
            widget: "string"
            hint: "URL to link to the project partner image."
          - name: "partner_image"
            widget: "image"
            hint: "Partner image shown on the left hand side."
            media_library:
              config:
                multiple: false
      - label: "Body"
        name: "body"
        widget: "markdown"
        hint: "Main page body of the project. If you wish to add custom widgets below this text, use the Page Sections below."
      - label: "Page Sections"
        name: "page_sections"
        widget: "list"
        hint: "Customize the project page using blocks (text-block, image-gallery-block, link-block, and video-block). You can drag these up and down to re-order the list of blocks."
        types:
          - label: "Text Block"
            name: "text-block"
            widget: "object"
            hint: "Markdown editor text block."
            fields:
              - {
                  label: "Text",
                  name: "text",
                  widget: "markdown",
                  hint: "Enter your custom text.",
                }
          - label: "Image Gallery Block"
            name: "image-gallery-block"
            widget: "object"
            summary: "{{fields.image}}"
            hint: "Image gallery of images with captions."
            fields:
              - label: "Images"
                name: "images"
                widget: "list"
                summary: "{{fields.image}}"
                fields:
                  - label: "Image"
                    name: "image"
                    widget: "image"
                    hint: "Add an image you want to show in the gallery."
                  - {
                      label: "Description Text",
                      name: "string",
                      widget: "string",
                      hint: "Caption text describing the image.",
                    }
          - label: "Link Block"
            name: "link-block"
            widget: "object"
            hint: "Block of text and associated link buttons to link to external content."
            fields:
              - {
                  label: "Title",
                  name: "title",
                  widget: "string",
                  hint: "Title of the link block.",
                }
              - {
                  label: "Content",
                  name: "content",
                  widget: "markdown",
                  hint: "Custom text content shown above all the buttons. i.e. description of what the links are.",
                  required: false,
                }
              - label: "Buttons"
                name: "buttons"
                widget: "list"
                summary: "{{fields.text}} {{fields.url}}"
                hint: "Buttons associated with the text block."
                fields:
                  - {
                      label: "Text block",
                      name: "content",
                      widget: "markdown",
                      hint: "Text paragraph shown above the button.",
                      required: false,
                    }
                  - {
                      label: "Button Text",
                      name: "text",
                      widget: "string",
                      hint: "Button text shown on the action button.",
                    }
                  - {
                      label: "Link",
                      name: "url",
                      widget: "string",
                      hint: "URL that the button will open.",
                    }
          - label: "Video Block"
            name: "video-block"
            widget: "object"
            summary: "{{fields.title}}"
            hint: "Full width video element to embed YouTube videos into the project page."
            fields:
              - {
                  label: "Title",
                  name: "title",
                  widget: "string",
                  hint: "Title of the block (leave blank if you don't want a title to appear).",
                  required: false,
                }
              - {
                  label: "Caption",
                  name: "caption",
                  widget: "markdown",
                  hint: "Caption displayed below the video.",
                  required: false,
                }
              - {
                  label: "Video Embed Code",
                  name: "video_embed_code",
                  widget: "text",
                  hint: "Paste in video embed code (see https://support.google.com/youtube/answer/171780?hl=en-GB)",
                  required: false,
                }
              - {
                  label: "YouTube Video ID",
                  name: "youtube_video_id",
                  widget: "string",
                  hint: "Paste the YouTube video ID to show as full width video (Important: e.g. enter MM6ZPrJDBO8 rather than https://www.youtube.com/watch?v=MM6ZPrJDBO8).",
                  required: false,
                }
          - label: "Quote Block"
            name: "quote-block"
            widget: "object"
            summary: "{{fields.quote}}"
            hint: "Large caption quote block to display"
            fields:
              - {
                  label: "Quote",
                  name: "quote",
                  widget: "string",
                  hint: "Quote text to display (keep this short).",
                }
              - {
                  label: "Attribution",
                  name: "attribution",
                  widget: "string",
                  hint: "Person(s) you are attributing the quote to (optional).",
                }
              - {
                  label: "Align Text",
                  name: "align",
                  widget: "select",
                  options: ["left", "center", "right"],
                  required: true,
                }
  - name: "project-types"
    label: "Project Types"
    files:
      - label: "Project Types"
        name: "project-types-config"
        file: "content/project_types.json"
        fields:
          - label: "Project Types"
            name: "project-types"
            widget: "list"
            hint: "Specify the project types you'd like to use in your projects."
            fields:
              - { label: "Project Type", name: "type", widget: string }
