backend:
  name: github
  repo: think-active-labs/not-equal # Path to your Github/Gitlab repository
  branch: main # Branch to update
  base_url: https://not-equal-netlify-cms-github-oauth-provider.vercel.app # Path to ext auth provider

media_folder: public/uploads

collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "About"
        name: "about"
        file: "content/about.md"
        format: "frontmatter"
        fields:
          - {
              label: "Body",
              name: "body",
              widget: "markdown",
              hint: "Main content goes here.",
            }
      - label: "Home"
        name: "home"
        file: "content/index.md"
        format: "frontmatter"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Description", name: "description", widget: "string" }
          - { label: "Header Image", name: "image", widget: "image" }
          - {
              label: "Body",
              name: "body",
              widget: "markdown",
              hint: "Main content goes here.",
            }

  - name: "projects"
    label: "Projects"
    folder: "content/projects"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    format: "frontmatter"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - label: "Header Image"
        name: "header_image"
        widget: "image"
        media_library:
          config:
            multiple: false
      - label: "Project Lead(s)"
        name: "project_lead"
        widget: "list"
        summary: "{{fields.lead}} - {{fields.email}}"
        fields:
          - { label: "Project Lead", name: "lead", widget: "string" }
          - { label: "Project Lead Email", name: "email", widget: "string" }
      - label: "Co-investigator(s)"
        name: "investigators"
        widget: "list"
        summary: "{{fields.investigator}} - {{fields.email}}"
        fields:
          - { label: "Investigator", name: "investigator", widget: "string" }
          - { label: "Investigator Email", name: "email", widget: "string" }
      - label: "Partner Images"
        name: "partners"
        widget: "list"
        summary: "{{fields.name}} - {{fields.link}}"
        fields:
          - label: "Name"
            name: "name"
            widget: "string"
          - label: "Link"
            name: "link"
            widget: "string"
          - name: "partner_images"
            widget: "image"
            media_library:
              config:
                multiple: false
      - label: "Page Sections"
        name: "page_sections"
        widget: "list"
        types:
          - label: "Text Block"
            name: "text-block"
            widget: "object"
            fields:
              - { label: "Text", name: "text", widget: "markdown" }
          - label: "Image Gallery Block"
            name: "image-gallery-block"
            widget: "object"
            summary: "{{fields.image}}"
            fields:
              - label: "Images"
                name: "images"
                widget: "list"
                types:
                  - label: "Image"
                    name: "image"
                    widget: "image"
                  - {
                      label: "Description Text",
                      name: "string",
                      widget: "string",
                    }
          - label: "Link Block"
            name: "link-block"
            widget: "object"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Content", name: "content", widget: "markdown" }
              - label: "Buttons"
                name: "buttons"
                widget: "list"
                summary: "{{fields.text}}"
                fields:
                  - { label: "Text", name: "text", widget: "string" }
                  - { label: "Link", name: "url", widget: "string" }
          - label: "Video Block"
            name: "video-block"
            widget: "object"
            summary: "{{fields.title}}"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Caption", name: "caption", widget: "markdown" }
              - {
                  label: "Video Embed Code",
                  name: "video_embed_code",
                  widget: "text",
                }
              - { label: "Video URL", name: "video_embed_code", widget: "text" }
