---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: heading
  label: Pages
- type: document
  path: content/pages/home.md
  label: Home
- type: document
  path: content/pages/about.md
  label: About
- type: heading
  label: Themes
upload_dir: static/uploads
public_path: "/uploads"
front_matter_path: "/not-equal/uploads"
use_front_matter_path: true
file_template: ":filename:"
build:
  preview_output_directory: public
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run dev
